# Week 1

## 1. Introduction

### - Supervised Learning
: In supervised learning, we are given a data set and already know what our correct output should look like, having the idea that there is a relationship between the input and the output.
* Regression: predict continuous valued output
* Classification: discrete valued output

 

### - Unsupervised Learning
: Unsupervised learning allows us to approach problems with little or no idea what our results should look like. We can derive structure from data where we don't necessarily know the effect of the variables. With unsupervised learning there is no feedback based on the prediction results.
* Clustering
* Non-clustering: i.e. identifying individual voices and music from a mesh of sounds at a cocktail party

## 2. Model and Cost Function

### - Model Representation
* m : number of training examples
* x : input variable or features
* y : output variable or target variable
* (x, y) : single training example
* ($x_i$, $y_i$) : i-th training example


* hypothesis function(h)<br>
 : x -> hypothesis -> y<br>
 : $h(x) = \theta_0 + \theta_1x$ ($\theta$: parameters)

### - Cost Function (Mean Squared Error)
: We can measure the accuracy of our hypothesis function by using a cost function. This takes an average difference (actually a fancier version of an average) of all the results of the hypothesis with inputs from x's and the actual output y's.
* $J(\theta_0, \theta_1) = \frac{1}{2m} \sum_{i=1}^{m}(h(x_i)-y_i)^2$<br>
&nbsp;  -> simplify as $J(\theta_1)$ : function of $J(\theta_1)$ 


## 3. Parameter Learning

### - Gradient Descent

1. start with arbitrary parameters
2. update the parameters until convergence<br>
&nbsp;$\theta_j := \theta_j + \alpha\frac{\partial}{\partial \theta_j}J(\theta_0, \theta_1)$,  &nbsp; $\alpha$: learning rate
* Applying to the cost function,<br>
&nbsp; repeat until convergence: {
    $$\theta_0 := \theta_0 - \alpha\frac{1}{m}\sum_{i=1}^{m}(h(x_i)-y_i)$$
    $$\theta_1 := \theta_1 - \alpha\frac{1}{m}\sum_{i=1}^{m}(h(x_i)-y_i)x_i$$ 
    }<br>
 cf) 'Batch' Grdient Descent: Each step of grdient descent uses all the training examples.


## 4. Linear Algebra Review

### - Matrix Inverse
: must be a square matrix<br>
&nbsp; cf) Singular Matrix : A square matrix that does not have a matrix inverse.

In [11]:
import numpy as np
a = np.array([[3, 4], [2, 16]])
b = np.linalg.inv(a)        # Inverse Matrix
print(b)
print(np.matmul(a, b))      # Matrix Multiplication

[[ 0.4   -0.1  ]
 [-0.05   0.075]]
[[1. 0.]
 [0. 1.]]


### - Matrix Transpose

In [14]:
c = np.array([[1, 2, 0], [3, 5, 9]])
d = c.transpose()
print(c)
print(d)

[[1 2 0]
 [3 5 9]]
[[1 3]
 [2 5]
 [0 9]]
